packages:
  - apps/*
  - packages/*
catalog:
  elysia: ^1.4.22
  "@elysiajs/cors": ^1.4.1
  "@elysiajs/eden": ^1.4.6
  "@elysiajs/node": ^1.4.3
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  zod: ^4.1.11
  typescript: ^5.8.2
  "@types/node": ^22.13.11
  tsdown: ^0.15.5
  ai: ^6.0.0
  "@ai-sdk/openai": ^3.0.0
  "@ai-sdk/google": ^3.0.0
  "@ai-sdk/react": ^3.0.0
